import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from "../components/sharedstyles";
import { Cards } from "../components/cards";

import Image from "next/image";
import logoMegasena from "../public/megasena-icon.png";
import About from "../components/about";

export default function Home() {
  const [numeros, setNumeros] = useState([]);

  useEffect(() => {
    generateMegaNumbers();
  }, []);

  const generateFromRandomOrg = async () => {
    const response = await axios.get(
      "https://www.random.org/integers/?num=6&min=1&max=60&col=1&base=10&format=plain&rnd=new&unique=on"
    );
    const numeros = response.data.split("\n");
    numeros.pop();

    numeros.sort(function (a, b) {
      return a - b;
    });
    setNumeros(numeros);
  };

  const getRandomIntInclusive = (min: number, max: number) => {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  const generateMegaNumbers = () => {
    let array = [];
    const MAX_NUMEROS = 6;
    let i = 0;
    while (i < MAX_NUMEROS) {
      const numeroAleatorio = getRandomIntInclusive(1, 60);
      if (!array.includes(numeroAleatorio)) {
        array.push(numeroAleatorio);
        i++;
      }
    }
    array.sort(function (a, b) {
      return a - b;
    });
    setNumeros(array);
  };

  return (
    <Container>
      <Head>
        <title>Mega-Sena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Image
          src={logoMegasena}
          alt="Logo Mega-Sena"
          width={100}
          height={100}
        />
        <Title>Mega-Sena</Title>

        <Description>
          Os números que te deixarão rico(a) são:
          <CodeTag>
            {numeros.map((numero, index) => (
              <span key={index}>{numero} </span>
            ))}
          </CodeTag>
        </Description>

        <div style={{ display: "flex", marginTop: 40 }}>
          <Cards
            title="Gerar novos números com Math.random()"
            onClick={generateMegaNumbers}
            style={{ marginRight: 10 }}
          />
          <Cards
            title="Gerar novos números com a API do RANDOM.ORG"
            onClick={generateFromRandomOrg}
          />
        </div>

        <About />
      </Main>
    </Container>
  );
}
